### ISSUE TITLE
无法编译成功

### ISSUE THREAD

**Issue by xuan880** [gedeng/finaltun#1]
➜  ~ go get github.com/gedeng/finaltun/client
# github.com/gedeng/finaltun/client

atmpdir/go/user/src/github.com/gedeng/finaltun/client/main.go:151: cannot use key (type string) as type []byte in argument to kcp.DialEncrypted

➜  ~ go get github.com/gedeng/finaltun/server
# github.com/gedeng/finaltun/server

atmpdir/go/user/src/github.com/gedeng/finaltun/server/main.go:65: cannot use c.String("key") (type string) as type []byte in argument to kcp.ListenEncrypted

**Comment by tcz001** [comment]
是KCP更新了接口，已经修复了
